### ISSUE TITLE
Path in Dockerfile does not exist in the repository

### ISSUE THREAD

**Issue by nmoran** [DIUx-xView/xview2-baseline#2]
When building Docker image from Dockerfile it fails as there is no `xview-2` folder to add

```ADD xview-2 /code/xview-2```

If changed to

```ADD / /code/xview-2```

The build will work if the build context is set to the top level repository folder (default when building using dockerhub).

**Comment by deg4uss3r** [comment]
Thanks for putting in an issue @nmoran during development we built the image from a level above the xview2 repository and built with the call: 
`docker build -t cmu-xview2-baseline -f ./"$xview2-repository"/submission/Dockerfile .`

You're not seeing an `xview-2`, because you probably cloned as `xview2-baseline`.

Our steps are described in the  [README.md](https://github.com/DIUx-xView/xview2-baseline#docker-container).

However, I do have a [commit](https://github.com/deg4uss3r/xview2-baseline/commit/58d95075dbec8b29b4651dece233caf25dc33242) that I am currently testing locally that will fix this and use the public URLs for the baseline code, and weights. I should be able to merge that into master shortly. This will make building much easier.

**Comment by deg4uss3r** [comment]
Merged in the Dockerfile update, closing issue. If you have trouble with anything else please open a new issue :)
