### ISSUE TITLE
Problem with process_data.py

### ISSUE THREAD

**Issue by vadik6666** [DIUx-xView/xview2-baseline#6]
I followed the README instructions and failed at preprocessing step of [damage paragraph](https://github.com/DIUx-xView/xview2-baseline#damage-classification-training).
```
(xview) /xview2-baseline-master/model$ python process_data.py --input_dir /data/xview19/xBD/ --output_dir /data/xview19/xBD/damage_out --output_dir_csv /data/xview19/xBD/damage_out.csv --val_split_pct 0.80
INFO:root:Started Processing for Data
 24%|███████████████████████████████████████████████▉                                           Traceback (most recent call last):                                                                       | 1790/7323 [01:20<03:58, 23.23it/s]
  File "process_data.py", line 183, in <module>
    main()
  File "process_data.py", line 178, in main
    process_data(args.input_dir, args.output_dir, args.output_dir_csv, float(args.val_split_pct))
  File "process_data.py", line 116, in process_data
    label_file = open(label_path)
FileNotFoundError: [Errno 2] No such file or directory: '/data/xview19/xBD//spacenet_gt/labels/hurricane-harvey_00000258_pre_disaster.json'
 24%|███████████████████████████████████████████████▉                                                                                                                                                    | 1790/7323 [01:20<04:09, 22.19it/s]
```
What should I do?

**Comment by ni40in** [comment]
having the same issue actually. this is because "spacenet_gt/labels" contains .png files while process_data.py expects .json

**Comment by deg4uss3r** [comment]
Hi, and thanks for putting in an Issue. 

`spacenet_gt` is for the localization training, your classification training should **not** touch this directory. Please move it out of the original image directory so `process_data.py` can parse the original images and pull out the polygons. You can retrain the localization with `train_model.py`, because you give the path to the `spacenet_gt` directory it does not have to be alongside the original images to train. 

If you are still experiencing issues put in another ticket, or chat with us on the [Discord](https://discord.gg/Za9fSqu)
